variables:
  # Docker Variables
  hostname: "nexus.holydev.net"
  maintainer: "holt31"
  dockerimagename: "nmrih-server"
  dockersubfolder: "."
  version: "latest"

stages:
  - build_docker
  - restart_pods
  - get_logs
  - describe_pods

.before_script_build_docker:
  before_script:
    # Sometimes Dind svc seems too long to start and/or dind certs are long to be available on builder
    - mkdir -p /kaniko/.docker
    - echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json

build_docker_nmrih:
  extends: .before_script_build_docker
  stage: build_docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""] 
  # Build Docker-Image
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "$maintainer/$dockerimagename:$version"
      --destination "$hostname/$maintainer/$dockerimagename:$version"

  only:
    refs:
      - master